# coding: utf-8
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a[2]/@href').get()
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a[2]').get()
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a[2]')
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a')
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a/text()')
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a/@href')
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a/@href').get()
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a/@href').get()
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a[2]/@href').get()
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a/@text()').get()
next_page
next_page=response.xpath('//*[@id="user-repositories-list"]/div/div/a/text()').get()
